### ISSUE TITLE
Are point kinds useful?

### ISSUE THREAD

**Issue by aantron** [aantron/bisect_ppx#101]
If you use Bisect_ppx point kinds, please let us know. Otherwise, we may remove them.

<br/>

##### Background

Bisect_ppx currently has "match" points, "binding" points, etc., and breaks down coverage statistics by point kind (i.e. "your tests visited 53% of the functions, 17% of the match cases," etc).

I'm not aware of a use case for this information. I've already removed it from the HTML reports since January, and we got no complaints.

There is also some talk of removing them from other reports, because then the reports could be generated without reading the `.cmp` files (not to mention, IMO, the reports would become much cleaner).

**Comment by lindig** [comment]
I don't have special uses for the different kinds and could live without them. 

The one kind that I would find interesting is matching of exceptions in `try … with`. Are these subsumed under the existing kind `Match` or `Try`? I find calling `&&` a lazy operator a bit confusing. These logical operators evaluate arguments only as needed - so lazily in a sense. However, lazy evaluation in OCaml usually refers to the use of the `Lazy` module.

    type point_kind =
      | Binding (** Point kind for toplevel bindings). *)
      | Sequence (** Point kind for sequences, including [;], [|>], and [let]. *)
      | For (** Point kind for [for] loops. *)
      | If_then (** Point kind for [if/then] constructs. *)
      | Try (** Point kind for [try/with] constructs. *)
      | While (** Point kind for while loops.*)
      | Match (** Point kind for [match] constructs, and functions. *)
      | Class_expr (** Point kind for class expressions. *)
      | Class_init (** Point kind for class initialiazers. *)
      | Class_meth (** Point kind for class methods. *)
      | Class_val (** Point kind for class values. *)
      | Toplevel_expr (** Point kind for toplevel expressions. *)
      | Lazy_operator (** Point kind for lazy operators ({i i. e.} [&&] and [||]). *

**Comment by rleonid** [comment]
I think that as a maintainer they're a bit onerous, but when I first encountered them I thought they might be of interest to a code quality type tool that allows you to see the different structures in a large code base. For example, 

- if you encounter a lot of `Sequence` (or `While`) elements, are you mutating a lot of state? 
- Or what is the percentage of `Try` (withs) that are present in the code base, signifying that some logic is being communicated (maybe too frequently) via an exception.

And I agree with @lindig that the use of `Lazy` in this case is unfortunate, but they may be of interest; bI find that long `&&` or `||` typically encode some subtle logic that might be better suited for a pattern match. So, they may be useful for _another_ tool but worth jettisoning for the simplicity of maintaining `bisect_ppx`.

**Comment by aantron** [comment]
> Are these subsumed under the existing kind Match or Try? I find calling && a lazy operator a bit confusing.

Agreed about `Lazy_operator`, and I would have the same question about `Match`/`Try`. This is precisely the problem with maintaining (or explaining) point kinds. Too often, it's not clear which construct should be which point kind. Some of them seem to overlap. And, when we change the way Bisect instruments code, do we then have to mess with, or reinterpret the point kinds? And so on. We've already had some brief such discussions.

> So, they may be useful for another tool but worth jettisoning for the simplicity of maintaining bisect_ppx.

I agree with this. It seems like the use cases @rleonid mentioned are best served by a linter – perhaps [`ocamllint`](https://github.com/cryptosense/ocamllint)?

**Comment by aantron** [comment]
Want to clarify:

> The one kind that I would find interesting is matching of exceptions in try … with. Are these subsumed under the existing kind Match or Try?

These are marked as `Try`. I think @rleonid gave an implicit answer to this question, but I wanted to restate it.
