### ISSUE TITLE
Suggestion: change extension of .out files

### ISSUE THREAD

**Issue by aantron** [aantron/bisect_ppx#110]
This is probably a bad idea because it will break every single use of Bisect_ppx.

However, I always found it annoying that the extension is `.out`.
- It conflicts with `a.out` when trying to run simple tests.
- It's easy to collide with output of other tools.
- It's not descriptive.

Any thoughts?

<br/>

- [x] ~~Announce upcoming change to `.coverage` in 1.5.0~~.
- [x] Make the change in 2.0.0.
- [x] Show a message if the reporter receives a `.out` argument, or no file arguments.

There is no need to have a soft transition, because it's more effort than just making the transition.

**Comment by lindig** [comment]
I share your observation. The `*.out` extension is traditionally used by C compilers and a bad choice for that reason. Something like `.bsct` or similar would be better. Strictly spoken, it is taken, according to this: https://www.file-extensions.org/search/?searchstring=bsct but `.bisect` would be free.

**Comment by aantron** [comment]
We should probably get moving on this.

1. In the next release, add a PPX option `-new-extension` that causes Bisect_ppx to output `.out` files. Add a nag to the PPX if the option is not supplied. Alternatively, or additionally, we can add a nag to `bisect-ppx-report` if it is given `.out` files. Link to this issue from the nag. This softly informs the users and encourages them to gradually adapt their build system.
2. In 2.0.0, make `.bisect` the default.
3. In 2.0.0 or a later release, nag users to stop passing `-new-extension`.

**Comment by aantron** [comment]
@rleonid Any thoughts on the extension? I'm suggesting `.bisect`. Do you think it would cause any problems?

**Comment by rleonid** [comment]
I wouldn't bother with a nag and just change the extension (`.bisect` is fine with me).
If we add the appropriate note to changes and maybe an `opam` message for the new versions we should fine.
