### ISSUE TITLE
documentation for file format

### ISSUE THREAD

**Issue by hannesm** [aantron/bisect_ppx#114]
is the file format generated by running the application under test documented somewhere?  if so, I'd appreciate a pointer to that.  thx!

**Comment by aantron** [comment]
It's not documented anywhere, but you can see the reading code for version 1.1.0 [here](https://github.com/aantron/bisect_ppx/blob/1.1.0/src/library/common.ml#L192). `master` [differs](https://github.com/aantron/bisect_ppx/pull/108) somewhat.

Each `.out` file is a [magic identifier](https://github.com/aantron/bisect_ppx/blob/1.1.0/src/library/common.ml#L141) followed by a `Marshal`led `(string * int array) array`, an array of pairs of:

- source filename, and
- array of point visitation counts.

If you want to read this, depending on your environment, the best way might be to link with package `bisect_ppx.runtime` and call `Bisect.Common.read_runtime_data`. Note that I am considering a better interface (#111).

**Comment by hannesm** [comment]
thx! I was hoping to (easily) read it from elisp..  but Marshal is unfortunately very much compiler-version dependent, which makes it a bit hard...

**Comment by aantron** [comment]
We can turn this into an issue for making the file format less dependent on OCaml.

**Comment by hannesm** [comment]
well, if Marshal is convenient for you, I guess I can deal with it (currently low on time in any case, this was just an idea I had days ago -- I dislike having to switch from editor to web browser to view the coverage information)... also, I could try an emacs plugin written in ocaml using janestreet's ecaml

**Comment by aantron** [comment]
It is convenient for Bisect_ppx. It can be annoying to use a format, e.g. JSON, because we are trying to avoid dependencies in Bisect_ppx (since it might complicate the building of those projects, if they ever wanted to use Bisect). But, ultimately it's better to be convenient for Bisect's users, and your idea sounds cool :) So, if you are coming back to this at some point, you are welcome to prod me/others to get it switched. Ideas for a format to avoid dependencies are welcome as well.

If you finish a plugin, let us know and we can link to it.

**Comment by aantron** [comment]
For now, this issue is basically about adding to [`doc/advanced.md`](https://github.com/aantron/bisect_ppx/blob/master/doc/advanced.md) the information at the [top of this issue](https://github.com/aantron/bisect_ppx/issues/114#issuecomment-246787880).

**Comment by brendanlong** [comment]
If you used atdgen to generate JSON, I think it would only be a build dependency.

**Comment by aantron** [comment]
I think in this issue we wanted to read it as well, but if we just have a JSON report, then yes :)

**Comment by hannesm** [comment]
as time passed, I suddenly wanted that feature again, and wrote a sexp-outputter #192 (plus the emacs lisp glue)

**Comment by aantron** [comment]
This simple module

https://github.com/aantron/bisect_ppx/blob/8af03e4f526606a9c094badee932d009889b7ec8/src/common/bisect_common.ml#L40-L76

and this line

https://github.com/aantron/bisect_ppx/blob/8af03e4f526606a9c094badee932d009889b7ec8/src/common/bisect_common.ml#L151

probably serve as documentation for the `.out` file format at the moment. However, as can be seen, it has changed considerably recently, and I think we prefer not to commit to it nor to document it. New reporters like #192 are welcome :)
