### ISSUE TITLE
dumping coverage data based on a trigger

### ISSUE THREAD

**Issue by edwintorok** [aantron/bisect_ppx#122]
In some cases it might be useful to dump coverage data sooner than `at_exit` (for C applications you could call `__gcov_flush` to do that).
For example: long running daemon that needs to stay alive to run more testcases.

Signal handling might be an option (optionally based on an env var), if both bisect_ppx and the actual program take care of calling the old signal handler in the newly installed one.
Another one would be listening on a socket/fifo but that requires the Thread module.

What are your thoughts? Would a PR that adds a signal handler be good?

**Comment by aantron** [comment]
That would be pretty useful indeed.

My guess would be that Bisect can't make decisions about threads or signal handlers inside its own runtime. That's too likely to interfere with applications.

It should probably expose some variant of [[this code]](https://github.com/aantron/bisect_ppx/blob/master/src/library/runtime.ml#L81-L83) somehow, and document it. The application/tester can then call that however it sees fit.

What do you think?

**Comment by edwintorok** [comment]
Yes, it would be better to expose a function in the mli. Although using it would require some sort of conditional compilation, so that it won't fail if `Bisect.Runtime.write_dump` is not available when not compiling with coverage.

**Comment by aantron** [comment]
That's a good point. I forgot about this complication. Not sure what the best thing to do here is, but setting an environment variable to a signal number or fd now sounds much more reasonable.

There is some talk of changing the license. Maybe that will allow always linking Bisect, but provide a no-op runtime when coverage is disabled. I think that should work even in the presence of dependencies – `Bisect.Runtime.write_dump` should only need to be called by top-level applications and test runners. In the case of applications/daemons that directly call `write_dump`, it would make Bisect no longer only a `{test}` dependency, however.

**Comment by aantron** [comment]
IIRC this was resolved by #129, so closing it. Please let me know if that's inaccurate.
