### ISSUE TITLE
Proper Unicode support

### ISSUE THREAD

**Issue by aantron** [aantron/bisect_ppx#127]
Consider (line 3) [here](https://yoichihirai.com/vmtest-coverage-20170106/file0000.html#L3). I am not sure if this is the fault of Bisect_ppx, the compiler, or something else, but ideally we wouldn't produce corrupted characters like that.

**Comment by emillon** [comment]
I tried to reproduce this with `master` and it did not have the problem. My best guess would be that the original file (https://github.com/pirapira/eth-isabelle/blob/master/lem/evm.lem), encoded as UTF8, was re-saved as latin1. The current situation is that if the source code is encoded as UTF8, the HTML report is UTF8, which seems like a reasonable state.

**Comment by aantron** [comment]
Great, thanks for looking at that!
