### ISSUE TITLE
Add [@@@coverage exclude file]

### ISSUE THREAD

**Issue by gaborigloi** [aantron/bisect_ppx#130]
I have surrounded the whole contents of a file with `(*BISECT-IGNORE-BEGIN*)` and `(*BISECT-IGNORE-END*)` comments. Previously the file had 0.01% coverage, but with these comments, the while had 100% coverage, both in the locally generated HTML report and on coveralls, however, I wanted to make the file completely disappear from the coverage report. (I used the comments to exclude the file from coverage analysis, because this way it will always work without having to specify the `.exclude` file.)
I used `bisect_ppx` 1.2.0 from opam.

**Comment by aantron** [comment]
Perhaps we should special-case this, or add a new kind of comment for ignoring entire files. It does seem like a lighter-weight, and probably easier to maintain, option than passing arguments to Bisect or using `.exclude` files.

**Comment by aantron** [comment]
Thinking about this more, since we are in the PPX era, maybe a better way is to exclude the file if `[@@@bisect.exclude_file]` is found somewhere in the file, rather than a comment. This goes back to the suggestion by @alainfrisch that we archived in #83. A true PPX shouldn't have to read the concrete syntax of the input file.

@gaborigloi, @rleonid let me know any opinion on this. I still have to think about how `[@@@...]` would interact with `#line` directives, since those are on the lexical level.

**Comment by aantron** [comment]
> I still have to think about how `[@@@...]` would interact with #line directives, since those are on the lexical level.

Ok, it looks like there is no interaction. Bisect_ppx reports things as in the file that is in the filesystem, whose path was given to Bisect, not as in the file as indicated by `#line` directives. This might be weird for some kinds of generated files, but I suppose it's the only thing that truly makes sense with the locations found throughout the AST.

So, the `[@@@...]` should be fine.

**Comment by rleonid** [comment]
I think it would be fine. I've used the `#line` directives to join the a `.ml` file with a `.mlt` file that contains the testing logic ala the original [kaputt](http://kaputt.x9c.fr/). But since I immediately ask to ignore the test code it has no impact.

**Comment by gaborigloi** [comment]
That sounds good to me, I don't think that we use the `#line` directive.

**Comment by aantron** [comment]
The attached commit added `[@@@coverage exclude file]`. If you place this anywhere in the file's top-level module, coverage will be disabled for the file completely, and it will not appear in the coverage report at all.
