### ISSUE TITLE
Change the license to something less frightening

### ISSUE THREAD

**Issue by aantron** [aantron/bisect_ppx#133]
We don't believe that the license of Bisect actually affects distribution of any code that uses it, but we would like to avoid hesitation and confusion. My default go-to license is 3-clause BSD, but any other such license (MIT, Apache, etc.) should be good. I believe @xclerc, @rleonid, and myself already agree on doing this; please post which license you prefer or any objections.

**Comment by aantron** [comment]
(the current license being GPL v3)

**Comment by rleonid** [comment]
I think at one point I had a good reason to favor Apache over the ones you mentioned; but I can't recall at the moment, so we can roll with 3-clause BSD for simplicity.

**Comment by aantron** [comment]
Well, let's leave this open for a while. If you remember the reason, post it :)

**Comment by xclerc** [comment]
I usually use either GPL or LGPL (even though I never completely
understood the static linking exception).

**Comment by hcarty** [comment]
FWIW my preference in descending order would be:
1. MIT
2. 3-clause BSD
3. Apache 2

**Comment by aantron** [comment]
@hcarty might giving a brief explanation, or maybe links to such?

**Comment by hcarty** [comment]
@aantron Simplicity, honestly.  From a personal standpoint MIT is very easy for me to look at and understand.  BSD-3 is similar in scope but more wordy.  And Apache 2 is long, possibly for good legal reasons.  From a legal standpoint I don't have much insight other than having seen all of them accepted at multiple commercial shops.

https://choosealicense.com/ provides some nice summaries as well.

**Comment by aantron** [comment]
Reviewing the licenses, I am starting to agree with @hcarty that we should choose MIT, mainly due to simplicity. My next choice would be LGPL or MPL if we want to prevent closed-source use of modified Bisect, but practically speaking I don't think this is likely, and if it happens, it's likely not to be a threat to open-source Bisect. @xclerc, what do you think (and others)?

**Comment by xclerc** [comment]
Indeed, I see no threat... The thing is, I find dubious to allow people
to "sell copies" of an open source software. That being said, I would
not oppose to MIT if there is a majority supporting it.

**Comment by aantron** [comment]
I also find that strange (but IIRC even the various GPL licenses allow it, as long as source is available). I just did a brief search, and couldn't find any reference to an instance where the MIT license was abused.

**Comment by xclerc** [comment]
The GPL licenses do allow it but, by requesting the source to be
available, guarantee that the developer next door will be able to
publish the very same code at no charge... thus ruining the
tentative business...

Anyway, not an issue, just my two cents.

**Comment by hcarty** [comment]
(as an aside - @xclerc My understanding is that the static linking exception exists because the OCaml compiler statically links OCaml code.  So without this exception there is effectively no difference between the GPL and LGPL for OCaml projects.)

**Comment by aantron** [comment]
I definitely would like to require that any modified version of Bisect be made available for us to take patches from. But the business about linking in LGPL is confusing to begin with, and the exception needed by OCaml makes it even worse.

Maybe the Mozilla Public License 2.0 is the right answer here?

Does anyone have experience with MPL? Do corporate users accept it? Are users familiar enough with it? It is a bit lengthy, so if familiarity is low, we may have to explain it in one sentence in the `README`.

cc @bobzhang for any opinion on MPL.

**Comment by hcarty** [comment]
The zeromq project is working to move from LGPL+linking exception to MPL 2. There are some notes at the following link and a lot of other discussion on the bug tracker and mailing list.

http://zeromq.org/area:licensing

**Comment by xclerc** [comment]
If the Wikipedia page is accurate, MPL 2 is actually very interesting (will
read ZeroMQ bugtracker / mailling list threads later on). 

It is actually pretty much what I was aiming for (however, it was probably a
failure due to the linking exception - thanks @hcarty for the clarification).

**Comment by aantron** [comment]
Ok, I propose we switch to MPL 2.0 for the imminent 1.3.0 release. I'll add text to the `README` and each announcement, which will be some variation on:

> Bisect_ppx is available under the Mozilla Public License 2.0 (MPL). To summarize, you can incorporate Bisect_ppx into proprietary projects. If you make modifications to Bisect_ppx, you have to open-source them. The rest of the project remains proprietary.
>
> Essentially, this is like the BSD or MIT licenses, except that if you customize Bisect_ppx, you have to contribute the changes back, or keep them in a visible fork.

I'm a bit worried about the length, language, and lack of familiarity with this license for more casual users. Hopefully, the summaries will overcome any hesitation (or some users might not care about the license at all :p).

I suppose if we find out that MPL is a poor choice, we can change the license again in a future release, even though it's somewhat annoying.

**Comment by aantron** [comment]
It may also be worthwhile to link readers to the MPL FAQ: https://www.mozilla.org/en-US/MPL/2.0/FAQ/
