### ISSUE TITLE
Restore self-instrumentation

### ISSUE THREAD

**Issue by aantron** [aantron/bisect_ppx#140]
We use this to generate the coverage report *of* Bisect *by* Bisect. It's both part of Bisect testing, and a nice demo.

Self-instrumentation was originally added in #51 and removed in #117 while porting to Jbuilder/ocaml-migrate-parsetree.

- [x] Set it up by creating a Dune workspace for it on the fly.
- [x] Submit coverage to Coveralls from an `allowed_failures` row.
- [ ] Add a badge to the README.

**Comment by aantron** [comment]
I'm closing this for now. It doesn't seem to be easy to do in a maintainable fashion.

The instrumenting (meta) Bisect needs its module and package renamed, to something like `Meta_bisect`/`meta_bisect_ppx`. It needs to know to refer to itself by that name when compiling the reporter and instrumenter and referring to the runtime.

The instrumented (under test) Bisect needs, I think, only an extra dependency on `meta_bisect_ppx`.

I'm not aware of an easy way of achieving this, except by copying the source and applying patches, and that seems annoying to maintain.

**Comment by rleonid** [comment]
Would it be possible to do with different versions? Maybe in a local opam switch?

**Comment by aantron** [comment]
The biggest problem is that when programming a program under test, instrumenting it with Bisect_ppx, Bisect_ppx causes the program to refer to a module `Bisect` (the runtime).

However, when that program is Bisect_ppx itself, it already has a module `Bisect` (and, indeed, we want to instrument *that* module, too). So, we need to rename the meta-runtime to something other than `Bisect`, so it can work with the runtime under test.

I guess one way around this is to never link the runtime into anything except programs under test (it is currently also referenced by other code, due to containing `Bisect.Common`). If we keep the runtime sufficiently simple, we can skip self-instrumenting it, and self-instrument only everything other than the runtime.

I think we will still have to change the name of the meta-package, though, to be able to refer to it without confusing Jbuilder.
