### ISSUE TITLE
Should ppx_tools_versioned be a runtime dep?

### ISSUE THREAD

**Issue by aantron** [aantron/bisect_ppx#142]
Looking at the [`bisect_ppx.opam`](https://github.com/aantron/bisect_ppx/blob/07a994f6bbe8724ad62e77b75f2c326810da33ea/bisect_ppx.opam#L30) file, we have:

    "ppx_tools_versioned" {build}

Meanwhile, `instrumentPpx.ml` [depends on module `Ppx_tools_404`](https://github.com/aantron/bisect_ppx/blob/07a994f6bbe8724ad62e77b75f2c326810da33ea/src/syntax/instrumentPpx.ml#L20), which is from `ppx_tools_versioned`.

For the standalone PPX, the PPX is built, and it doesn't matter after that that it needed `ppx_tools_versioned`. However, for linking the PPX library into a driver, do we need to insist that `ppx_tools_versioned` remain installed (i.e. it is not a build-time dependencency)?

cc @rgrinberg

**Comment by rgrinberg** [comment]
Anton, that analysis looks correct. It should be a regular dependency

**Comment by aantron** [comment]
Ok, I made this into an easy issue about removing the `{build}` text from the `bisect_ppx.opam` file. We'll get this in before release. Thanks for confirming.
