### ISSUE TITLE
Do we need to include the filename in ___bisect_mark___?

### ISSUE THREAD

**Issue by aantron** [aantron/bisect_ppx#148]
@rleonid, looking at [this](https://github.com/aantron/bisect_ppx/blob/2008454de776246bac85d3467245259695658e6e/src/syntax/instrumentPpx.ml#L52-L54):

```ocaml
let custom_mark_function file =
  Printf.sprintf "___bisect_mark___%s"
    (* Turn's out that the variable name syntax isn't checked again,
       so directory separtors '\' seem to be fine,
       and this extension chop might not be necessary. *)
    (Filename.chop_extension file)
```

I don't think we need to append the filename to `___bisect_mark___`, because `___bisect_mark___` is local to the current module anyway. It looks fragile with respect to the future, in that we may need name mangling in a future version of the compiler.

I believe it was added in 0cce616583552ae7cce08485a98b217f73c0e938, part of #23, working on resolving #3. Please let me know if I am missing something in my reasoning.

**Comment by rleonid** [comment]
If I remember correctly, I added the filename appending when I was munging several test files into one. In retrospect, that seems like an unnecessary act and probably one better handled by smarter compilation. So yea, it is superfluous.

The comment was to clarify that we can have variables such as `__bisect_mark__directory\file1`.

**Comment by aantron** [comment]
Including the filename is correct; see #160.
