### ISSUE TITLE
Cannot find opam package bisect_ppx-ocamlbuild

### ISSUE THREAD

**Issue by KasperJanssens** [aantron/bisect_ppx#150]
The instructions in the Readme.md suggest to install bisect_ppx-ocamlbuild when working with myocamlbuild. However, I am not able to find this package in the opam repository (https://opam.ocaml.org/packages/). So I was wondering then where I should find it? Or is it not necessary anymore?

This is more of a question than a bug of course.

**Comment by aantron** [comment]
@KasperJanssens It's not necessary *yet*. Sorry about that. The plan was to release `bisect_ppx` 1.3.0 and concurrently `bisect_ppx-ocamlbuild`, but life and other work is interfering, so there is a delay :/

For now, if you install `bisect_ppx` alone, it's enough to get the plugin, and that will remain the case for a few months after `bisect_ppx-ocamlbuild` is released. That will give you a window to switch over to depending on that package. We will announce both the release of `bisect_ppx-ocamlbuild`, and the later point at which it becomes the only way to get the plugin.

I'll revert the docs not to mention `bisect_ppx-ocamlbuild` for now.

**Comment by aantron** [comment]
Ok, instructions should be in sync with reality now. Thanks for asking this.

I'd like to leave this issue open as a reminder to un-revert the instructions during release :)

**Comment by KasperJanssens** [comment]
Alright, thanks for the quick response :-)
