### ISSUE TITLE
Coverage report: what  is the exact meaning of the 'white' lines in the report?

### ISSUE THREAD

**Issue by KasperJanssens** [aantron/bisect_ppx#152]
More of a question than an issue, but I see a lot of white lines in my coverage report, next to green and red. I take it green are lines that have been touched by a test, red have not been touched, but what is the meaning of the white lines, the unmarked ones?

**Comment by aantron** [comment]
Bisect_ppx works by expressions. For example, if you have a single line

```ocaml
if foo (bar ()) = 3 then f () else g ()
```

Then Bisect_ppx thinks that you might want to know

1. Whether the whole `if` is reached,
2. Whether `bar ()` returns,
3. Whether the `then` case is reached,
4. Whether the `else` case is reached.

So it instruments all the relevant subexpressions. Actually, it's not quite thorough enough yet. We have an issue about fixing what exactly gets instrumented here: https://github.com/aantron/bisect_ppx/issues/82.

So, in general, each line has several instrumented points of interest. The lines in the report are then highlighted as follows:

1. Green lines are those that have instrumented expressions, and all of them were visited.
2. Red lines have instrumented expressions, and none were visited.
3. Yellow lines have instrumented expressions, and some were visited, but others not.
4. White lines don't have instrumented expressions (comments, whitespace, or subexpressions that Bisect_ppx currently doesn't think are worth instrumenting).

Besides adjusting what gets instrumented (#82) and maybe changing the appearance of the report, we should probably also document this. So, I'd like to leave this issue open. Thanks for asking!

**Comment by aantron** [comment]
I've modified the `README` to include a summary of what the colors mean.
