### ISSUE TITLE
Prepare to change the name

### ISSUE THREAD

**Issue by aantron** [aantron/bisect_ppx#157]
From @bluddy on [Discourse](https://discuss.ocaml.org/t/bisect-ppx-ocaml-code-coverage-with-nice-html-reports/728/4):

> Any chance of renaming to something like coverage_ppx? Bisect_ppx gave me the completely wrong idea about the project.

I have to agree with this. I don't know how practical changing the name is, but I also think Bisect is not really right for a coverage tool (@xclerc?).

There have also been suggestions to drop the `_ppx` suffix (@rgrinberg?), but the original Bisect and package `bisect` still enjoy apparently wide use. At the very least, they support Camlp4.

<br/>

- [ ] New opam package (`coverage_ppx`?).
- [ ] Rename repo.
- [ ] Announce on Discuss and elsewhere.
- [ ] Ask people for better ideas?

There is no need to have a soft transition here.

**Comment by rleonid** [comment]
> the completely wrong idea about the project.

It may not be precise but it isn't completely wrong. I think that as long as there is a regular `bisect` package, this package has a clear meaning.

**Comment by xclerc** [comment]
There is indeed some confusion because of what "bisect" means in a VCS.

For the record, I originally used the tool to "bisect" by using operations on
coverage files. Roughly speaking, if you subtract a run from another one,
you get the locations exercised only by one specific run. You can hence,
by successive subtractions determine the code that produces a bug.

**Comment by aantron** [comment]
I figured this is how it got the name :) We removed combine expressions some time ago, as they were not being used by anyone. Instead, I suggest that we add some kind of way to delimit coverage statistics, #131. This would probably only be truly useful with good support from testing frameworks, though.

**Comment by aantron** [comment]
I want to abandon this. Most users seem fine with Bisect_ppx, even if it's awkward. There is a concern of discoverability, but I did various Google and DuckDuckGo searches for "ocaml coverage" and similar queries, and never had any trouble finding Bisect_ppx. `opam search coverage` also works well.

We don't have a great replacement name, and it's not worth breaking the continuity.
