### ISSUE TITLE
Index out of bounds caused by the new source code

### ISSUE THREAD

**Issue by aantron** [aantron/bisect_ppx#160]
This isn't really a complete bug report, more a reminder to self to fix it later. If someone would like details, please ask.

The development version of Bisect_ppx, applied to Markup.ml, causes a failure with index out of bounds.

**Comment by aantron** [comment]
So, the cause of this is the subject of #148, "Do we need to include the filename in `___bisect_mark___`?" The answer is *yes* :)

`___bisect_mark___` has since been renamed to `___bisect_visit___`.

Using the same name `___bisect_visit___` in each module produces the following interaction when a module without an `.mli` file is `open`ed by another one:

`foo.ml`:

```ocaml
let ___bisect_visit___ =
  (* Creates an array of 10 elements for point counts. *)
```

`bar.ml`:

```ocaml
let ___bisect_visit___ =
  (* Creates an array of 20 elements for point counts, because
     this file has 20 points. *)

open Foo
(* Just shadowed ___bisect_visit___. *)

(* ... *)

___bisect_visit___ 19
(* Index out of bounds in Foo.___bisect_visit___, which isn't the
   one we want called anyway. *)
```

So we'll have to revert the change that closed #148.

**Comment by rleonid** [comment]
ugh, I should have documented that better.

**Comment by aantron** [comment]
After thinking some more about the pitfalls of using paths in identifiers, name mangling, etc., I came up with this scheme:

`b.ml`:

```ocaml
module Bisect_visit___ =
struct
  let ___bisect_visit___ = (* ... *)
end

open Bisect_visit___
(* This open precedes any other open in the code. At the same time,
   since other modules have ___bisect_visit___ scoped, no other
   open can shadow it. This guarantees that ___bisect_visit___
   refers to b.ml's ___bisect_visit___. *)

open A
```

**Comment by aantron** [comment]
Ugh, this doesn't work either. Markup.ml is the Bisect killer.

The problem is that you can't include a module in another one, because you can't have two `Bisect_visit___` submodules.

**Comment by aantron** [comment]
Ok, I decided to mangle the filename and append it to the module name `Bisect_visit___`. I think that's better than messing with the name of `___bisect_visit___` and having it unscoped for several reasons:

- Due to the above structure, these `Bisect_visit___` modules and their `___bisect_visit___` functions still can't interfere on `open`.
- If two mangled `Bisect_visit___` module names collide, it is a compile-time error. This is caused by module inclusion only. By contrast, if two mangled `___bisect_visit___` functions collide, one silently shadows the other. This may or may not appear at *runtime*, as the bug described in this issue. Collision of `___bisect_visit___` functions can happen both on module inclusion and module open. If shadowing of `___bisect_visit___` does not cause the bug in this issue, it can result in inaccurate coverage statistics.
- Mangling `Bisect_visit___` involves only the generated module declaration and immediate `open`, so in the instrumenter, the mangling can be kept local to the function that generates the top of each instrumented file. Mangling `___bisect_visit___` has to be done everywhere `___bisect_visit___` is used, which complicates the instrumenter slightly by comparison.

This all has resulted in new interesting test cases. I will post the PR shortly.
