### ISSUE TITLE
Line directives

### ISSUE THREAD

**Issue by rleonid** [aantron/bisect_ppx#168]
I've been rethinking [this](https://github.com/aantron/bisect_ppx/commit/f7244ce0cb33d29c0fba36e5ebe88fb9f48ca266), in terms of a way of incorporating into jbuilder. I've tried out one scheme where I use jbuilder's `copy#` to isolate the piece of code that I want to test. Unfortunately, bisect_ppx ignores the directive, so the attribution is "wrong."

I think that this is part of a larger problem of what is the *best* way of incorporating tests into OCaml projects. I'm on the fence with respect to how expect tests are incorporated into the source code  as I like to isolate them into a separate source file, but I'm struggling with having a good end to end solution.

**Comment by aantron** [comment]
I'm not sure what to do about line numbers, but concerning expect tests, I prefer to write them in a different file. This is mainly because a really thorough test suite ends up quite large, and I usually don't want it polluting the source.

**Comment by aantron** [comment]
I'm closing this, since we aren't working on it. Please reopen if closing is wrong :)
