### ISSUE TITLE
presence of .exclude file should not matter when bisect is disabled

### ISSUE THREAD

**Issue by gtrak** [aantron/bisect_ppx#169]
This is a multi-project interaction, but I think bisect_ppx's responsibility is to simply not break when it's not actually doing any work.

What's expected to happen:
Bisect and jbuilder play nicely, and paths are properly sorted out so that merlin can work.

What happens:
merlin is run without any knowledge of your project root, so absolute paths are required in .merlin.  There is proof of the issue with ppx drivers themselves and a hard-coded solution for that case: https://github.com/ocaml/merlin/issues/699

But this is not enough when the ppx requires external configuration files. 

The external effects with merlin is to show errors like 'extension 'map' not supported'.

I have filed a corresponding jbuilder issue to be able to absolutize the location of the .exclude file: ocaml/dune#712

It seems to me that bisect is not needed during development time when it's being used conditionally, therefore it shouldn't break if configured improperly at that time.  Can we add a check or early-exit or something that avoids this problem?

Here's how it's being invoked in our jbuild:
```
  (preprocess (pps (ppx_jane bisect_ppx -conditional
                    (-exclude-file email_report/src/.exclude))))
```

And I would like the behavior when the bisect environment variable is unset to just pass things through regardless of configuration.

**Comment by gtrak** [comment]
Thoughts? https://github.com/arenadotio/bisect_ppx/pull/1/files

**Comment by gtrak** [comment]
I verified that the fix works and merlin is fine now.

**Comment by aantron** [comment]
Thanks for reporting :) The fix looks good, would you mind sending it as a PR against this repo as well?

**Comment by gtrak** [comment]
sure!
