### ISSUE TITLE
Percentage rounding ends up causing confusion

### ISSUE THREAD

**Issue by IagoAbal** [aantron/bisect_ppx#172]
In an HTML report, the index page shows the percentage of coverage points visited per file. This percentage is rounded to have no fractional digits. Problem is, if the percentage is `99.5%` or higher, this will show up as `100%` causing some confusion. Of course, even rounding to two fractional digits may cause the same problem.

I propose a minor change of this line
https://github.com/aantron/bisect_ppx/blob/1114b91b04307cbd2dd040bc992bea5bc2a310cb/src/report/report_html.ml#L75
to `"percentage", Report_utils.(Printf.sprintf "%d/%d (%.02f%%)" stats.visited stats.total (percentage stats)) ]`.

And also a minor change of this line
https://github.com/aantron/bisect_ppx/blob/1114b91b04307cbd2dd040bc992bea5bc2a310cb/src/report/report_html.ml#L90
to `["p", Report_utils.(Printf.sprintf "%d/%d (%.02f%%)" stats.visited stats.total (percentage stats));`.

(Lines 71 and 85 would need to be changed to remove the added percentage `%` symbol.)

This would just mimic the format used in the text report:
https://github.com/aantron/bisect_ppx/blob/1114b91b04307cbd2dd040bc992bea5bc2a310cb/src/report/report_text.ml#L20

**Comment by aantron** [comment]
Thinking about this years ago, I thought we should round everything except 100% into the range [0-99]%. So 99.5% would be displayed as 99%. I think it would convey the right idea without displaying any more numbers. What do you think about that?

It also looks like right now, percentages less than 10 will get displayed with fractional digits. We probably don't want that, as it is the singles and tens places that are our significant figures in this display, and not the tenths or less-significant places.

**Comment by IagoAbal** [comment]
That sounds good too. My initial thoughts were to use arbitrary-precision arithmetic and so on, but I considered that over-complicated. Now I'm thinking that perhaps using `Pervasives.truncate` (aka `Pervasives.int_of_float`) would suffice, and it should be a minor change too. I would then suggest to perform no rounding, and truncate everywhere. Does it sound too drastic?

**Comment by aantron** [comment]
`int_of_float` sounds like probably the best idea. IIRC the only reason we even had two decimal points of precision on file pages and in the text report was to avoid rounding problems, and that gave enough significant figures for the number of coverage points in most files. Truncating should address rounding better.

**Comment by IagoAbal** [comment]
Then I think we have a simple and nice fix for this. Should I open a pull request?

**Comment by aantron** [comment]
Please, that would be very welcome :)

**Comment by IagoAbal** [comment]
I will open that pull request, it is in my to-do list (so I don't forget). I'll probably have time in August.

**Comment by aantron** [comment]
Thank you :)

**Comment by IagoAbal** [comment]
Thank you very much for resolving this issue. I feel a bit ashamed after having promised to fix it myself. I would have fixed it eventually, but I'm afraid my to-do list is a bit too long. :-)

**Comment by aantron** [comment]
No problem, it's understood as normal that there are often more important things to do :) Thanks for prompting it.
