### ISSUE TITLE
-conditional instrument code without BISECT_ENABLE=YES

### ISSUE THREAD

**Issue by NathanReb** [aantron/bisect_ppx#185]
It seems that since I upgraded to `bisect_ppx v1.4.0`, our ocaml code is always instrumented, even without setting `BISECT_ENABLE=YES`.

Downgrading it back to `v1.3.4` fixes the issue.

I unfortunately didn't manage to reproduce this on a minimal example yet but I'm working on it, I'll get back to you as soon as I'm able to do so!

I think it was worth mentioning anyway in case you'd be aware of a recent change that might have somehow impacted `-conditional` behavior.

**Comment by NathanReb** [comment]
Hmm my bad, after running a few experiment it appears that the problem indeed persists with `v1.3.4`.

I still can't reproduce it on a small project so it's a bit of a nightmare to debug.

**Comment by NathanReb** [comment]
Finally found it. The issue arises when using `bisect_ppx -conditional` within a `staged_pps` stanza.

That happened because I was using both `ppx_import` and `bisect_ppx` in a library and I don't know of any way around that yet.

I'm not sure whether this requires fixing in `dune` or `bisect_ppx` but my guess would be the former. I'll report it there as well.

**Comment by NathanReb** [comment]
It was indeed a bug in dune, sorry for the inconvenience!

**Comment by aantron** [comment]
Thanks for looking into it!
