### ISSUE TITLE
Support for cobertura report

### ISSUE THREAD

**Issue by ulrikstrid** [aantron/bisect_ppx#189]
I'm trying to integrate reporting in Azure DevOps but they only support Cobertura and JaCoCo. Looking at the different outputs cobertura seems more "sane" to me but I can go either way.

If I could get some pointers I could probably do the work unless someone else is eager to do it.

Example output: https://raw.githubusercontent.com/jenkinsci/cobertura-plugin/master/src/test/resources/hudson/plugins/cobertura/coverage-with-data.xml

**Comment by aantron** [comment]
I'd suggest using the Coveralls report as a model, https://github.com/aantron/bisect_ppx/blob/master/src/report/report_coveralls.ml. The linked Cobertura report looks much more structured than what you can readily produce with Bisect_ppx. Bisect_ppx doesn't give context about methods, branches, etc. It only gives a list of locations for each file. On the other hand, Bisect_ppx gives locations with both lines and columns, which I don't see an example of in the linked report, so Cobertura supports at most one point per line. This is a limitation of Coveralls as well. All of these differences are probably strongly influenced by differences between OCaml and the typical imperative+OO languages.

**Comment by ulrikstrid** [comment]
It seems like Azure DevOps wants to support something simpler and are working on it.

Did some more research and my guess is that lcov or some richer json format than coveralls might make the most sense because then there are a bunch of tools that can convert from that to the other formats.

I won't pick this up at the moment, I will instead wait and see what happens in Azure DevOps, feel free to close this if you want to.

**Comment by aantron** [comment]
Thanks. We can reopen it later, once there is more information from Azure DevOps, if you'd like to work on it again :)
