### ISSUE TITLE
Change license again, to MIT (sorry!)

### ISSUE THREAD

**Issue by aantron** [aantron/bisect_ppx#199]
@rleonid, @xclerc: two years ago, we changed the license to MPL (#133). The feedback I've gotten about it over time is that most people don't know what MPL is, so the license continues to be a source of some confusion.

I suggest again we change it to MIT. What are your opinions on this now?

I don't think we will have any problems from using the MIT license.

- [x] Change the license (and switch to Markdown).
- [x] Update `.opam` file.
- [x] Remove license explanation from the README.
- [ ] Update license headers.

**Comment by rleonid** [comment]
Fine by me.

**Comment by xclerc** [comment]
No objection from my side.

**Comment by aantron** [comment]
Thanks!
