### ISSUE TITLE
Figure out the Dune integration

### ISSUE THREAD

**Issue by aantron** [aantron/bisect_ppx#203]
- [ ] https://github.com/ocaml/dune/issues/2573
- [ ] https://github.com/ocaml/dune/issues/57

References:

- https://github.com/ocaml/dune/pull/419
- https://github.com/ocaml/dune/pull/616
- https://github.com/ocaml/dune/issues/391
- https://github.com/ocaml/dune/pull/168

**Comment by aantron** [comment]
@rgrinberg, I think in order to do #136, Bisect_ppx will have to output an extra file when it preprocesses source, i.e. preprocessing `foo.ml` would output not only the `foo.pp.ml` expected today by Dune, but also `foo.coverage-metadata`, or something like that.

As I understand it, Dune will delete `foo.coverage-metadata` during a rebuild of the project. Is that right?

**Comment by rgrinberg** [comment]
Dune would indeed delete it. The list of modules that were linked seems like something should be able to answer however. We could imagine a `$ dune build foo.exe.unlinked-modules` for example. Would this help at all?

**Comment by aantron** [comment]
It would help slightly, in that at least we could report that there are some modules for which coverage wasn't generated at all due to not being linked. But the "gold standard" would be to have the coverage metadata available for those modules, so we can simply generate the normal report for them, with all the coverage points unvisited. For that, we need to dump the metadata (location info) somewhere, and the reporter needs to load it.

**Comment by aantron** [comment]
Actually, that issue might be even more difficult to solve, even with the help of Dune, because we still can't "fix" the case where a module is not even in the dependency cone, so isn't even preprocessed in the first place. I'll have to think about it more. The best thing to do might be nothing.

**Comment by aantron** [comment]
What I would want, based on my experience to date:

1. Don't add special hardcoded support for Bisect_ppx.
2. Project developers should opt into coverage. I don't find this problematic at all, because there are few `dune` files, and project structure rarely changes. Opting in is the easiest option to understand, because it doesn't require learning any hidden rules about where Bisect gets applied.
2. We don't want Dune controlling the order of when Bisect gets applied. We had an issue in Bisect recently about changing the order from first to last, and we are able to deal with this using OMP's API. Special handling would make this kind of change difficult.
3. We just need a simple and general mechanism for inserting S-expressions into `(preprocess (pps ...))`.
4. Use a variable, `(preprocess (pps {:bisect}))`. Please correct me if the syntax is wrong.
5. Set the variable in a `coverage` profile in `dune-project`:

   ```
   (env
    (coverage
     (flags -g -opaque)
     (:bisect (bisect_ppx --flags))))
   ```

   I'm not sure about the exact syntax.

   This allows setting the command line in one place. It also allows for each `dune` file to specify other PPXs, by listing them after `{:bisect}`.

   `{:bisect}` (or whatever variable) should expand to nothing if undefined (i.e., when not using the `coverage` profile) The `preprocess` stanza needs to be prepared for no atoms after `pps`.

6. A build with instrumentation is triggered with `dune build --profile coverage`.
7. All other builds are unaffected by this scheme. Dune never looks for Bisect_ppx or links it in other builds, so Bisect truly becomes a `{dev}` dependency in opam terms, requiring no manual handling during release.
8. My only remaining concern is that in a workspace, if there are multiple projects with `coverage` profiles, I typically want only one that I'm focusing actually built with coverage. This is minor, though.

Using `env` was originally proposed by @jberdine in https://github.com/ocaml/dune/pull/419#issuecomment-386535109.

@nojb, is this scheme suitable for landmarks?

**Comment by aantron** [comment]
Closing this. There is now progress in ocaml/dune#57. We will update the Bisect docs afterwards.
