### ISSUE TITLE
Support [@coverage off] in patterns

### ISSUE THREAD

**Issue by aantron** [aantron/bisect_ppx#246]
This should make it easy to exclude whole cases from coverage.

- [ ] Ordinary patterns.
- [ ] Or-patterns.
- [ ] If the expression in a case has coverage disabled, the case should not be instrumented.

**Comment by aantron** [comment]
Abandoning for now, as the original motivation was addressed in #247.

**Comment by cristianoc** [comment]
Quick question that might be related to this issue, guessing from the title.
Suppose there's a systemic source of uncovered code, that you know about and would like to filter out from the rest of the coverage reports, to reduce noise w.r.t. other parts that you care about more.
In my specific case, there are verbose/logging modes which are mostly used during debugging. While it would be possible to test under various combinations of those, it does not seem worth it.

So imagine just a bunch of `if(verbose) { ...log some message... }` scattered throughout the code base.

**Comment by aantron** [comment]
At the moment, you could tag those with `[@coverage off]`, like

```ocaml
(if(verbose) { ... }) [@coverage off]
```

(or however it will look exactly in Reason). I suggest to try this, and ping again if it turns out to be too repetitive/awkward somehow. It's more related to #198 than this issue, but probably a new issue is best.

**Comment by aantron** [comment]
Closing this for now. It can be reopened when needed.
