### ISSUE TITLE
modules ignored ?

### ISSUE THREAD

**Issue by zapashcanon** [aantron/bisect_ppx#264]
Hi,

Looking at [this report](https://coverage.zapashcanon.fr/opazl/), it looks like the modules `Ast` and `Pp` are ignored, see the [source](https://git.zapashcanon.fr/zapashcanon/opazl/).

In the case of `Pp` it may be because I'm not using any value from it in my tests. For `Ast` I'm not sure.

Is there a way to force `bisect_ppx` to generate coverage for all modules of a library as soon as this library is instrumented ?

**Comment by aantron** [comment]
Files instrumented with Bisect_ppx self-register, so if a file is not linked into your final tester executable, it won't appear at all in the report. See https://github.com/aantron/bisect_ppx/issues/136.

Solving this well requires some kind of build system support, but every solution I've considered so far has bad corner cases in complex projects. I'll give it some thought again, but it may take a while.

**Comment by aantron** [comment]
Bisect_ppx 2.0.0's reporter will have two flags, `--expect` and `--do-not-expect`, to help sanity-check the list of covered files on the Bisect side:

https://github.com/aantron/bisect_ppx/blob/02dfb10188033a26d07d23480c2bc44a3a670357/src/report/report.ml#L725-L750

The idea is that when the project constructs its reporter command (in a `Makefile` or similar), it can optionally add these arguments:

https://github.com/aantron/bisect_ppx/blob/02dfb10188033a26d07d23480c2bc44a3a670357/Makefile#L100-L103

I hope this is enough for the typical project, where most code is in one or a few directories, and there are some subdirectories or specific files to exclude.

Something more "intelligent," that inspects which files are actually linked into a library, requires build system support, so we probably can't solve it in this repo, at least not primarily.
