### ISSUE TITLE
generating an svg file with the coverage percentage

### ISSUE THREAD

**Issue by zapashcanon** [aantron/bisect_ppx#265]
Hi,

It's a feature request to have a svg file generated, which could look like [this](https://s3.amazonaws.com/assets.coveralls.io/badges/coveralls_100.svg). Is this something you'd be willing to add ?

Cheers.

**Comment by aantron** [comment]
Bisect_ppx itself already [uses](https://github.com/aantron/bisect_ppx#readme) such badges from [shields.io](https://shields.io/), where you can [make your own SVG badge](https://shields.io/#your-badge) and download it. My first suggestion would be to use `bisect-ppx-report summary` or `bisect-ppx-report summary --per-file`, extract the coverage number using `tail` and/or `awk`, and submit a request to shields.io to generate the badge.

**Comment by aantron** [comment]
Closing this issue, as I assume the above helped. Please comment if not.
