### ISSUE TITLE
Bisect fails on let-bind syntax

### ISSUE THREAD

**Issue by jobjo** [aantron/bisect_ppx#266]
I believe this is because the current latest version (1.4.1) preprocesses with `ppx_tools_versioned.metaquot_405` and should be resolved by publishing the latest master.

The issue I'm hitting is for code like:

```ocaml
let ( let* ) = Option.bind
let _ = let* x = Some () in x
```
and a dune file:

```ocaml
(library
 (name testbisect)
 (public_name testbisect)
 (preprocess (pps bisect_ppx -conditional -no-comment-parsing)))
```

It fails with:

```
(cd _build/default && .ppx/fd8acca92aaadae9d8099f94851fc84c/ppx.exe -conditional -no-comment-parsing --cookie 'library-name="testbisect"' -o src/hello.pp.ml --impl src/hello.ml --dump-ast)
Fatal error: exception File "src/hello.ml", line 3, characters 8-12: let operators are not supported before OCaml 4.08
```

**Comment by aantron** [comment]
Indeed, thanks. I haven't tried this with `master`, but I expect it to work. I need to finish some tasks to get it into a releasable state, so I can't give a timeline for releasing `master`. If critical, I can make a branch of 1.4.1 with the latest AST, and you should be able to proceed by pinning that. IIRC the AST port is pretty trivial. 88d24c5f3168d5e35e54fea6aa0da4fb694d49a6 upgraded from 4.05 to 4.08 and 02dfb10188033a26d07d23480c2bc44a3a670357 upgraded to 4.09. You may even be able to get this working by simply cherry-picking these commits locally, though I am not sure how much the surrounding code had already diverged from 1.4.1. Please let me know if there is any trouble and/or you'd like me to make the branch.

**Comment by aantron** [comment]
...it's probably best, actually, to make a 1.4.2 release branched from 1.4.1, with these commits cherry-picked in. I'll do that shortly.

**Comment by jobjo** [comment]
> ...it's probably best, actually, to make a 1.4.2 release branched from 1.4.1, with these commits cherry-picked in. I'll do that shortly.

Sounds good. Many thanks!

**Comment by aantron** [comment]
The release PR is https://github.com/ocaml/opam-repository/pull/15689. Closing in favor of tracking that. Thanks again!
