### ISSUE TITLE
Environment variable to toggle the PPX

### ISSUE THREAD

**Issue by vphantom** [aantron/bisect_ppx#267]
Related to #203, maybe this project could do like [Landmarks](https://github.com/LexiFi/landmarks) with its `$OCAML_LANDMARKS` environment variable.   Users could leave `bisect_ppx` in `dune` files at all times and, to get a coverage-enabled build:

```sh
dune clean ; OCAML_BISECT=auto dune build @all
```

Then for a production release, without the environment variable the PPX would stand down and not inject anything at all:

```sh
dune clean ; dune build @all
```

It's fairly clean and doesn't require any change in Dune. The only drawback is that projects structured this way would depend on `bisect_ppx`, which for my use is an acceptable compromise since it doesn't affect the compiled output in release mode.

**Comment by aantron** [comment]
@vphantom If I understood correctly, this is already what [`BISECT_ENABLE`](https://github.com/aantron/bisect_ppx#dune) does.

**Comment by aantron** [comment]
Perhaps the README should clarify the variable's exact effect. IIRC we had that in an earlier version of the docs, but it got lost somewhere in an effort to simplify them.

**Comment by vphantom** [comment]
Thank you for clarifying.  What confused me was that step 4 of the Dune section of the README mentions removing the `(preprocess ...)` rule from the `dune` file for a production release (awaiting its issue 57).

Going down in the Real-world example section, I now see that indeed, `--conditional` tells the PPX to pass through untouched when the `BISECT_ENABLE` environment variable isn't set.

I'll attempt a quick PR to reword this.
