### ISSUE TITLE
Add a section in the readme on how to avoid generating bisect_ppx docs 

### ISSUE THREAD

**Issue by Risto-Stevcev** [aantron/bisect_ppx#292]
I'd submit a PR but I don't know where you'd want to place this info. If you're writing an ocaml lib that's cross-compatible with native and bucklescript, then these are some docs on how to prevent odoc from picking up the `bisect_ppx` docs from `node_modules`:

for dune < 1.6
```
(ignored_subdirs (node_modules))
```
for dune > 1.6
```
(data_only_dirs node_modules)
```

**Comment by aantron** [comment]
I added only the >= 1.6 instructions for brevity, because I figured that is already a pretty old version of Dune. If someone deliberately supports an even older version, I suppose they will be comfortable with checking the Dune docs.
