### ISSUE TITLE
Provide an example of a Dune file in OCaml syntax

### ISSUE THREAD

**Issue by aantron** [aantron/bisect_ppx#294]
...which works around Dune not supporting a development-only PPX, https://github.com/ocaml/dune/issues/57.

**Comment by aantron** [comment]
@nobrowser, @anuragsoni, @Risto-Stevcev: I just changed the README instructions for Dune; they now [recommend using Dune's OCaml syntax](https://github.com/aantron/bisect_ppx#Dune):

```ocaml
(* -*- tuareg -*- *)

let preprocess =
  match Sys.getenv "BISECT_ENABLE" with
  | "yes" -> "(preprocess (pps bisect_ppx))"
  | _ | exception _ -> ""

let () = Jbuild_plugin.V1.send @@ {|

(library
 (public_name my_lib)
 |} ^ preprocess ^ {|)

|}
```

I changed the [starter repo](https://github.com/aantron/bisect-starter-dune) accordingly, as a minimal example, and there is also a tidy [patch](https://github.com/aantron/bisect-starter-dune/commit/24ffb2153d3c42ff166c78a9f55095bd12f10f4e#diff-cabdb1014252d39ac018f447e7d5fbc2) showing the difference to `dune` files.

Doing it this way seems to work pretty well:

- There is no need to edit for release.
- No need for cleaning when switching between coverage and non-coverage builds. Dune seems to know which files need updating.

We've already been [using this in odoc](https://github.com/ocaml/odoc/blob/master/src/parser/dune) for a while (I had forgotten). The odoc version is slightly less tidy :)

I also just switched to Lwt to doing this (back, actually, we did this also in Lwt at some point in 2017 or so): https://github.com/ocsigen/lwt/commit/7baf8b973c6a14e807a0ca83403a1a66d7bf2a32

**Comment by Risto-Stevcev** [comment]
@aantron I figured out that since I'm writing a cross-compat library for bs + native, I don't actually need to have it run for native since I'm ensuring code coverage on the bs side. I just add it as a `:with-test` dependency and have it generate on the bs side instead. It might be worth noting that workflow in the docs because bucklescript folks won't be able to upgrade to the latest dune (stuck on 2.2.0 for bs) and would have to use the tuareg mode

**Comment by aantron** [comment]
I'll keep this in mind for the future, for when there is a version of Dune that can offer a better Bisect integration on the native side.
