### ISSUE TITLE
Sending to Coveralls fails on generated lexer

### ISSUE THREAD

**Issue by modlfo** [aantron/bisect_ppx#299]
Hi,

I'm moving from ocveralls to using `bisect-ppx-report send-to Coveralls`. In my case the sending the data failed with the following error
```
*** system error: src/parser/lexer.ml: No such file or directory
```

I'm using ocamlbuild, and that file is generated by ocamllex from the file `src/parser/lexer.mll`. Seems like bisect_ppx is unaware that the file is generated and only exists inside the build directory.

Is there a way of excluding the file?

**Comment by aantron** [comment]
You may be able to work around this first by using

```
       --source-path=DIRECTORY
           Directory in which to look for source files. This option can be
           specified multiple times. File paths are concatenated with each
           --source-path directory when looking for files. The default
           directories are ./ and ./_build/default/. If running inside an esy
           sandbox, the default/ directory in the sandbox is also included.
```

So `--source-path=build` or `--source-path=_build`, according to what the build directory is named in your project. This will likely allow the reporter to find the generated file.

The next option, if that fails, is

```
       --ignore-missing-files
           Do not fail if a particular .ml or .re file can't be found.
```

To completely exclude the file from coverage, you can use the PPX [`--exclusions`](https://github.com/aantron/bisect_ppx/blob/9f899a64c4dbd78c2b11dc5c9aa5d169fbc7135f/doc/advanced.md#excluding-generated-files-from-coverage) option.

**Comment by aantron** [comment]
You also can use the [Ocamlbuild plugin](https://github.com/aantron/bisect_ppx-ocamlbuild#bisect_ppx-ocamlbuild-plugin) (if not already), and then it should be easy to exclude the file from coverage by untagging it.

**Comment by modlfo** [comment]
Thank you!

Providing `--source-path _build` works fine!
