### ISSUE TITLE
Set default values for BISECT_FILE and BISECT_SILENT at instrumentation time

### ISSUE THREAD

**Issue by mbouaziz** [aantron/bisect_ppx#302]
My tests aren't all launched from `dune`, and I may forget to set these environment variables, though they are known at compile time.

So ideally, I would like either ppx arguments or other variables, e.g. `DEFAULT_BISECT_FILE`, which would hardcode the value in the instrumented code.

Of course it wouldn't make sense if several instrumented files indicate different values, and I don't know what to do in this case: fail hard, use either one, ...

What do you think?

**Comment by aantron** [comment]
You should be able to set both of these environment variables programmatically in the tester like so: https://github.com/aantron/bisect_ppx/blob/master/doc/advanced.md#naming-the-output-files. Does that work for you?

**Comment by mbouaziz** [comment]
In my project, tests are run from different places (`dune`, `pytest`, etc. and why not even directly) and there isn't always a test-specific code where I could set the environment variable.

**Comment by aantron** [comment]
Ok. It's possible to add two options to the PPX, to hardcode default values of these variables. If the variables are also found in the environment, they will override the hardcoded values.

**Comment by mbouaziz** [comment]
I can do it. What do when several files have different values still need to be decided.

**Comment by aantron** [comment]
I think we can just let them race. Whichever module is the last to register with the runtime and pass in values will decide what the values will be.
