### ISSUE TITLE
Support BuckleScript ## method calls

### ISSUE THREAD

**Issue by aantron** [aantron/bisect_ppx#308]
See https://github.com/aantron/bisect_ppx/issues/307#issuecomment-612679619.

Docs [here](https://bucklescript.github.io/docs/en/object-2#call).

cc @wyze

**Comment by wyze** [comment]
Awesome, thanks! I'll watch for updates on this issue.

**Comment by aantron** [comment]
This should now be fixed in release 2.3.1, which is now in npm.
