### ISSUE TITLE
Figure out how to add a global exit hook in Jest

### ISSUE THREAD

**Issue by aantron** [aantron/bisect_ppx#314]
...since it does not trigger `process.on('exit')`. See https://github.com/reazen/relude/pull/261#issuecomment-616281740, https://github.com/aantron/bisect_ppx/issues/307#issuecomment-612654444.

The current instructions require adding a line of code to every single Jest test file, which is not practical in projects with more than two or so. Apart from being annoying, it is easy to forget while adding new test files.

cc @jihchi

- [ ] Update Jest instructions in README.

**Comment by jihchi** [comment]
I've configured Jest's [`setupFilesAfterEnv`](https://jestjs.io/docs/en/configuration#setupfilesafterenv-array) and it works, please see [working commit](https://github.com/reazen/relude/pull/261/commits/3eb79cc9b466e808fee626b76cdf54c39b2ec14f).

Following is how I configure it:

1. Add a file called `jest.setup.js` next to Jest's config file (e.g. `package.json`, `jest.config.js`)

```js
const bisectRuntime = require("bisect_ppx/lib/js/src/runtime/bucklescript/runtime.js");

afterAll(() => bisectRuntime.write_coverage_data());
```

2. Add `jest.setup.js` to `setupFilesAfterEnv` field in Jest config file

```js
"setupFilesAfterEnv": ["./jest.setup.js"]
```

That is it.

**Comment by aantron** [comment]
I'll try (maybe tomorrow) to make Bisect detect `afterAll` and/or other Jest objects, and call `afterAll` automatically from Bisect's runtime. We can probably also have Bisect detect the existence of `process.on` as a fallback, and eliminate the need for any manual calls to `Bisect.Runtime.write_coverage_data` on Node.

**Comment by jihchi** [comment]
By the way, I tried to hook `Bisect.Runtime. write_coverage_data ` on Jest's [`globalTeardown`](https://jestjs.io/docs/en/configuration#globalteardown-string), it did not work.

**Comment by aantron** [comment]
I committed your suggestion (thanks!) to `master`, so the helper JS file is distributed with Bisect, and all the user has to do is add:

```json
"setupFilesAfterEnv": [
  "./node_modules/bisect_ppx/src/runtime/bucklescript/jest.js"
]
```

I wasn't able to eliminate the need for that so far.

I'll address the other Jest-related issues, and then do a release.

**Comment by aantron** [comment]
I guess it can just be

```json
"setupFilesAfterEnv": [
  "bisect_ppx/src/runtime/bucklescript/jest.js"
]
```
