### ISSUE TITLE
bs-jest - Cannot find module 'bisect_ppx/lib/js/src/runtime/bucklescript/runtime.js' from 'jest.js'

### ISSUE THREAD

**Issue by jihchi** [aantron/bisect_ppx#320]
When we use `bs-jest` and enabled `in-source: true` in `bsconfig.json`, for example:

```json
 "package-specs": [
    {
      "module": "commonjs",
      "in-source": true
    }
  ]
```

we will get an error when running the Jest:

```sh
 FAIL  __tests__/hello_test.js
  ● Test suite failed to run

    Cannot find module 'bisect_ppx/lib/js/src/runtime/bucklescript/runtime.js' from 'jest.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:299:11)

Test Suites: 1 failed, 1 total...
```

it seems like the generated path of `runtimes.js` has been changed because of `in-source` flag:

https://github.com/aantron/bisect_ppx/blob/d0666721e7456abd1f9f8cc211b2813a0b91dc80/src/runtime/bucklescript/jest.js#L1

(`runtime.js` reside in  `bisect_ppx/src/runtime/bucklescript/runtime.js`)

here is reproducible repo:
https://github.com/jihchi/bisect-starter-bsb-jest/tree/cannot_find_module_insource

**Comment by aantron** [comment]
Is it fixed if you modify `jest.js` to fall back to the other path if the `require` fails? With code along [these](https://stackoverflow.com/a/17566436/2482998) lines. If that works, I'd be happy to merge a PR for it.

**Comment by jihchi** [comment]
Nope, it does not work. 

It seems like Jest does not rely on node resolver:
![jest js — bisect (Workspace) 2020-05-02 21-06-47](https://user-images.githubusercontent.com/87983/80864997-f45f9f80-8cb8-11ea-970c-c7459c96961e.png)

**Comment by aantron** [comment]
A workaround may be to distribute two `jest.js` files, one for in-source builds, and one for out-of-source builds. But this seems pretty annoying. It would be nice to solve this with one file in some way.

**Comment by jihchi** [comment]
I'm not sure if this works but how about rewrite `jest.js` in OCaml/Reason? it looks like this:

```re
[@bs.val] external afterAll : (unit => unit) => unit = "afterAll";

afterAll(() => {
  Runtime.write_coverage_data();
  Runtime.reset_coverage_data();
});
```

here is relevant path of `in-source` flag for Jest `setupFilesAfterEnv`:

| `in-source: false` | `in-source: true` |
| ----------------- | ----------------- |
| `bisect_ppx/lib/js/src/runtime/bucklescript/jest.js` | `bisect_ppx/src/runtime/bucklescript/jest.js` |

**Comment by aantron** [comment]
That's a good idea!

My esy is currently broken with some permissions problem (and I can't seem to be able to reinstall it either). I don't have time to fix that or set up a VM for it in the immediate days. esy is what builds the development binaries for the npm package. If you'd like a speedy fix, would you mind trying this? To run the BuckleScript test, you can do `make -C test/bucklescript full-test` in a clone of the repo.

To test a development Bisect against an npm package locally, probably the most reliable way is to do the same thing that the test does: `npm pack` in the root directory, then copy the tarball over to the Jest project, and `npm install bisect_ppx-2.4.0.tar.gz` (or whatever it will be called).

**Comment by aantron** [comment]
The code in OCaml syntax should be something like

```ocaml
external afterAll : (unit -> unit) -> unit = "afterAll"
  [@@bs.val]

let () =
  afterAll (fun () ->
    Runtime.write_coverage_data ();
    Runtime.reset_coverage_data ())
```

Not 100% sure because that's where I ran into the esy problem, and then spent all my remaining available time trying to debug that instead.

**Comment by jihchi** [comment]
I would like to give it a try to fix the issue. thanks for the instruction and explanation to getting started.
