### ISSUE TITLE
Prepare for Dune integration

### ISSUE THREAD

**Issue by aantron** [aantron/bisect_ppx#323]
ocaml/dune#57 has an initial solution. Among other issues, coverage output and/or source code are likely to appear in `_build/coverage` rather than `_build/default`, so the Dune integration on the Bisect end should be slightly adjusted to search for files in directories other than `_build/default`.

Outstanding upstream issues:

- [x] ~~https://github.com/ocaml/dune/issues/3472~~
- [x] https://github.com/ocaml/dune/issues/3473
- [x] https://github.com/ocaml/dune/pull/3535

Then:

- [x] ~~Adjust default coverage search paths~~
- [ ] Update Dune instructions
- [ ] Deprecate `--conditional`

**Comment by hannesm** [comment]
Hey @aantron, I was interested in this (and it looks like dune 2.6.0 with that feature was released some time ago). What is the status of bisect and dune (an update to the README and instructions would be highly welcome). Thanks :)

**Comment by aantron** [comment]
@hannesm It is currently waiting for the release of https://github.com/ocaml/dune/pull/3535 :)

**Comment by hannesm** [comment]
thanks @aantron, I was not aware of that PR -- looking forward getting there :)

**Comment by hannesm** [comment]
friendly ping; AFAICT that has been merged and is part of the dune 2.7.0 release merged recently to opam-repository. thanks :)

**Comment by undu** [comment]
I've gotten the instrumentation integration [working](https://github.com/undu/bisect_ppx/tree/dune27), but it requires dune 2.7. What are the opinions regarding this new requirement to enable this integration?

**Comment by aantron** [comment]
If the change is backwards-compatible, in that the existing older integration method still works, we can ask users to require `"dune" >= 2.7` in the Bisect README. As I recall, we used to do this for earlier versions of Dune for other reasons. @undu, is this what you mean?

**Comment by undu** [comment]
Yes, that's what I meant.

While the previous integration still works, the new integration requires ppx_bisect to be built using at least dune 2.7.0, it doesn't matter if the new or the old integration is used.

**Comment by aantron** [comment]
Is there a change to the code of Bisect that requires Dune 2.7.0 even if the old integration is being used? If yes, then we have to require Dune 2.7.0 in Bisect. If not, we can ask the user to require Dune at least 2.7.0 in the README if they are using the new integration. If that becomes a pain, we can still move the constraint up to Bisect later. However, in the past, it has seemed to work well, because we just put the Dune dependency into the example of how to depend on Bisect as well, i.e.

```
depends: [
  "bisect_ppx" {dev & >= "2.0.0"}
  "dune" {>= "2.7.0"}
]
```

**Comment by undu** [comment]
> Is there a change to the code of Bisect that requires Dune 2.7.0 even if the old integration is being used?

Yes. It's the field in the ppx's dune that marks it as instrumentation.

`(instrumentation.backend (ppx bisect_ppx))`

**Comment by aantron** [comment]
Ah right, then constraint in Bisect's `opam` it is.

**Comment by aantron** [comment]
@undu I've pulled your commits into a PR (#331). I'll finish it off with some testing and updating the README. Thanks for getting most of the change done!

**Comment by undu** [comment]
Thanks for continuing the work! I feel bad I dropped the ball there.

**Comment by aantron** [comment]
Ok, this is now in `master`. I'll finish editing the README (needed to merge without it to break dependency cycles with outside example projects), then solve some of the outstanding bugs, and then release this in Bisect_ppx 2.5.0. Thanks again, @undu.

**Comment by hannesm** [comment]
@aantron (and @undu) thanks for your work on this. it would be great to get the dune support released to opam-repository, anything I can do to help getting there? I saw the README was updated with the new instructions...

**Comment by aantron** [comment]
@hannesm I just need to get around to fixing some of the other issues, and then do the release. It's definitely coming up :)

**Comment by aantron** [comment]
This is now in opam (and npm) in Bisect_ppx 2.5.0. I've updated all the starter repos and the README.
