### ISSUE TITLE
bisect report generator unable to handle symlink cycles

### ISSUE THREAD

**Issue by rgrinberg** [aantron/bisect_ppx#324]
## Step to Repro

* Clone my dune fork, checkout the `bisect` branch. https://github.com/rgrinberg/jbuilder/tree/bisect

* run `$ make coverage`

* produce report with (base) `$ bisect-ppx-report html`
The following error will appear:

```
 *** system error: ./_build/default/test/blackbox-tests/test-cases/github764/symlink-outside-root2/other/a/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x: Too many levels of symbolic links
```

## Expected behavior

I would expect the reporter to ignore such circular symlinks, or provide a way to ignore them. I can't easily move them out of the repo because they're required for a test.

**Comment by aantron** [comment]
The linked commit should fix this. It's not an ideal fix, as I think if there are `.coverage` files in the symlink loop, the reporter will load all of them before finally stopping when it gets `Sys_error`. This causes it to waste time and to report inaccurate visitation counts, as it will sum the visitation counts from all the "separate" `*.coverage` files. This does not affect the main coverage statistic of which and how many points are visited at all, however.

I'm not aware of anyone who uses visitation counts at the moment, and I also expect valid `.coverage` files inside symlink cycles to be an extremely rare occurence, so I think this is enough for an initial fix.
