### ISSUE TITLE
Support Cobertura output format

### ISSUE THREAD

**Issue by arvidj** [aantron/bisect_ppx#326]
The [Gitlab code coverage visualization](https://docs.gitlab.com/ee/user/project/merge_requests/test_coverage_visualization.html) uses the [Cobertura](https://cobertura.github.io/cobertura/) format. Adding this type of output would ease simplify coverage visualization for OCaml projects.

**Comment by aantron** [comment]
For future reference, here is [example Cobertura output](https://gist.github.com/apetro/fcfffb8c4cdab2c1061d) and the [DTD](http://cobertura.sourceforge.net/xml/coverage-04.dtd). It seems considerably more complex that Coveralls format, and seems to make more assumptions about the source language.

**Comment by aantron** [comment]
[This example](https://istanbul.js.org/docs/advanced/alternative-reporters/#cobertura) might help with adapting Cobertura to OCaml.

**Comment by aantron** [comment]
Closing this issue as I won't have time to do it myself. @arvidj if you (or anyone else) would like to open a PR about this, I will be happy to review and merge it.

**Comment by sir4ur0n** [comment]
Assuming someone would be interested to give it a shot, do you have any advice/pointers/hints on how to proceed @aantron please? Ideally for someone who has not yet developed in `bisect_ppx` :grin:

**Comment by aantron** [comment]
It looks like you should be able to start by duplicating the [Coveralls formatter](https://github.com/aantron/bisect_ppx/blob/a72c5f244aa474f4110821943ce6e54c1f65bff6/src/report/report_coveralls.ml) and then modifying it.

If you work on this, please ping here, as I have plans to potentially work on this in the relatively near term, as well.

**Comment by sir4ur0n** [comment]
If you have plans to work on it I gladly leave the floor to you, as I think you would be significantly more efficient than me, considering you already know the code base :smile:

**Comment by vch9** [comment]
Just wanted to let you know I am starting to work on this feature!
