### ISSUE TITLE
Enable coverage on a project without modifying all the library dune file

### ISSUE THREAD

**Issue by aryx** [aantron/bisect_ppx#330]
Is there a way to get the bisect_ppx coverage without having to add the pps ppx_bisect to all the dune files
of libraries in a project? And how can I enable/disable it easily?
I look at the README which suggest adding some OCaml code to the dune file to look for an environment variable
but this seems heavy, especally if I have to put this OCaml blurb in all my dune files (I have a project with many many libraries).

There's also some traces here and there about a new --conditional flag, but it does not seem official yet (the top README does not mention this method). I also saw that dune itself has some special support for bisect in 2.7.0, but again it is not mentionned in the README.

Thx for this great project.

**Comment by aantron** [comment]
There's no way to do that presently, neither with the current recommended instructions, nor with the old `--conditional` flag (https://github.com/aantron/bisect_ppx/issues/329#issuecomment-699501047 on it), nor with the upcoming integration with Dune 2.7.0 (#323). All of those require editing all the `dune` files.

When discussing the design of the Dune integration, @rgrinberg proposed something like what you are suggesting &mdash; a way to apply Bisect to an entire project. I argued against it (at least, against it being the only or first option), but I think this issue should be treated at least as a vote in favor of supporting that after all.

The README will get updated with the Dune 2.7.0 instructions as part of #323.

**Comment by aantron** [comment]
Actually, the Dune docs have [this](https://dune.readthedocs.io/en/stable/instrumentation.html?highlight=instrumentation#enabling-disabling-instrumentation):

> To enable an instrumentation backend globally, you can type in your `dune-workspace` file:
>
> ```
> (lang dune 2.7)
> (instrument_with bisect_ppx)
> ```

This requires finishing #323 on the Bisect end, which I am working on right now. I'll post when I've tested that this works with the new integration.

**Comment by aantron** [comment]
Ok, so the above Dune instructions I linked to don't mark all libraries for coverage. They are just an alternative to the Dune command-line arguments `--instrument-with bisect_ppx`, and they still require you to manually edit `dune` files to enable coverage for specific libraries/executables. So my original comment stands; there is currently no way to request coverage globally at the moment. I suggest opening an issue on Dune to let them know you are interested in this.
