### ISSUE TITLE
dune & esy: Sys_error("./bisect.log: Operation not permitted")

### ISSUE THREAD

**Issue by davesnx** [aantron/bisect_ppx#337]
Hey @aantron, 

I'm moving to use the new bisect_ppx version with the combo of dune and esy and I encounter an issue.

I'm running rely which is the "reason-native" way of writing unit tests and It's a little different from dune runtest, so when I run the exe like this:

```esy b dune exec test/Run.exe --instrument-with bisect_ppx --force```

I found that bisect tries to create a file `bisect.log` and seems like there are no permissions to do so.

```Fatal error: exception Sys_error("./bisect.log: Operation not permitted")```

Thanks.

**Comment by davesnx** [comment]
As an obvious workaround, you can create the file to not trigger the crash. But would be cool to not have the issue.

**Comment by aantron** [comment]
Another workaround (from chat) is to use `BISECT_SILENT=ERR` or `BISECT_SILENT=YES`. However, it is better to understand and fix the problem instead :) Could you provide a repro for this, or some instructions, so I can debug it?

**Comment by davesnx** [comment]
I'm currently upgrading in here: https://github.com/davesnx/query-json/pull/27

**Comment by aantron** [comment]
It worked for me. I did:

```
git clone https://github.com/davesnx/query-json.git
cd query-json
git checkout I-25_Test-coverage
esy
esy b dune exec test/Run.exe --instrument-with bisect_ppx --force
esy bisect-ppx-report html
```

![Снимок](https://user-images.githubusercontent.com/12073668/97100395-2cfa9780-16a4-11eb-9805-0e3f1829274f.PNG)

**Comment by aantron** [comment]
Can you try with `BISECT_SILENT=ERR` so we can see what the underlying error is?

**Comment by davesnx** [comment]
I don't see the same.

```
esy bisect-ppx-report html

Error: no coverage files given on command line or found
```

Don't see anything different when I add those env vars on the command, neither `export BISECT_SILENT=ERR` neither `BISECT_SILENT=YES`.

**Comment by aantron** [comment]
But the command we are first debugging is

```
esy b dune exec test/Run.exe --instrument-with bisect_ppx --force
```

Is it still producing

```
Fatal error: exception Sys_error("./bisect.log: Operation not permitted")
```

even with the environment variables and with any other conditions you can vary? This command (the second to last in my sequence above) worked for me. Your last message does not say whether it is working now for you, in fact it makes me suspect that it is working, since you continued to the next command `esy bisect-ppx-report html`, but I am not sure if that's what I should get from the message.

**Comment by davesnx** [comment]
Yes, my bad. I ran the next command just to show that nothing gets generated. Running the test suit with instrument-with fails for me.

```bash
→ BISECT_SILENT=ERR esy b dune exec test/Run.exe --instrument-with bisect_ppx --force

Running 1 test suite
 PASS  correctly parse value

Test Suites: 0 failed, 1 passed, 1 total
Tests:       0 failed, 20 passed, 20 total
Time:        0.002s

Fatal error: exception Sys_error("./bisect.log: Operation not permitted")
```

Even after creating an empty `bisect.log`, I got the error of not permitted as well.

**Comment by aantron** [comment]
That you can't work around this using `BISECT_SILENT=ERR` makes me suspect we don't understand what is really going on. I think this is the only place in the code of Bisect that uses the string `bisect.log`:

https://github.com/aantron/bisect_ppx/blob/9bdc5dabad4c6d9f3115cf94ca7657058e10109b/src/runtime/native/runtime.ml#L34-L51

As you can see from this and surrounding code, if `BISECT_SILENT` is `ERR`, `verbose` should turn into a print to STDERR.

Can you instrument your copy of Bisect with prints to get a better idea of what is happening? Can you get a trace of attempted accesses to `bisect.log`? Are there multiple processes or OCaml threads running, each trying to write to `bisect.log`? Is there anything else like this you can investigate or think of? I'm not aware of esy having any global per-user configuration, but do you have anything that might make your esy different from, say, mine? Which version of esy are you using and on what OS?

**Comment by aantron** [comment]
@davesnx I will close this for now to tidy the tracker. Please post again if you have further information, and I'll look into it.

**Comment by davesnx** [comment]
Sure @aantron. I didn't debug closely the bisect runtime and ending up using a newer version and it's working great for me. Sorry for not posting it here!

**Comment by aantron** [comment]
No worries, glad it's working!
