### ISSUE TITLE
Update "advanced" help with new argument passing instructions

### ISSUE THREAD

**Issue by aantron** [aantron/bisect_ppx#356]
Now that https://github.com/ocaml/dune/pull/3932 is merged. Should probably wait until release so the minimal Dune version is known.

**Comment by aantron** [comment]
Blocked on https://github.com/ocaml/dune/pull/3932#issuecomment-734738991.

**Comment by aantron** [comment]
Still blocked, on https://github.com/ocaml/dune/issues/3983. It is currently not possible (AFAIK) to specify a file as a dependency of Bisect_ppx, the way it could be done previously when Bisect_ppx was a preprocessor and one could use `preprocessor_deps`.

**Comment by zapashcanon** [comment]
@aantron, it looks like this isn't blocked anymore, right ?

**Comment by aantron** [comment]
Thanks for the ping! I've updated the instructions.
