### ISSUE TITLE
Instrumentation breaks tail recursivity

### ISSUE THREAD

**Issue by monate** [aantron/bisect_ppx#359]
Hello,
On this example with Ocaml 4.11.1 and bisect_ppx 2.5.0 :
```Ocaml
let rec g y = g y || (g [@tailcall]) y
```
the instrumentation causes the Warning 51 to be emitted:
```Console
$ ocamlfind opt -c bisect_bug2.ml
$ ocamlfind opt -package bisect_ppx -c bisect_bug2.ml
File "bisect_bug2.ml", line 1, characters 21-38:
1 | let rec g y = g y || (g [@tailcall]) y
                         ^^^^^^^^^^^^^^^^^
Warning 51: expected tailcall
```
Tail recursivity preservation looks like something desirable for the bisect_ppx.

**Comment by aantron** [comment]
Indeed, the current instrumentation of `||` tries to discover whether either of the subexpressions evaluated to `true`, so it can display instrumentation for them that is similar to what Bisect does for or-patterns. I don't think there is a way to do that in general, while still preserving tail calls in the second subexpression.

This is what the instrumentation looks like right now:

https://github.com/aantron/bisect_ppx/blob/2fc5b795e603cde966a45343ef1b523234ce93d4/test/instrument/apply/or.t#L64-L86

The Bisect instrumenter already tracks whether expressions are in tail position or not. So the solution might be to suppress "fancy" instrumentation of the second expression if the whole `||` application is in tail position. I'll give it a bit more thought, then add a fix.

**Comment by monate** [comment]
Thanks for the feedback.
In my particular use-case, inhibiting the Warning 51 for instrumented blocks would probably be good enough.
In general, this looks like a trade-off between coverage precision and tail-call preservation: this may be left as an option to the end-user.

**Comment by aantron** [comment]
I chose to go for not instrumenting if in tail position in PR #362. This should be less fragile over time than suppressing `[@tailcall]`, which I think Bisect shouldn't do, as it suppresses users' intent.

I'll probably factor out the trivial functions check here:

https://github.com/aantron/bisect_ppx/blob/2fc5b795e603cde966a45343ef1b523234ce93d4/src/ppx/instrument.ml#L1166-L1206

and use it to avoid suppression in tail position of short predicates, i.e. in

`List.mem (fun e -> f e || e == 0)`

the `e == 0` is not in tail position, but it seems like it would be best not to suppress instrumentation here, but rather mark that branch.
