### ISSUE TITLE
Unbound module Marshal error when using with ReScript 9.1

### ISSUE THREAD

**Issue by JohnDoneth** [aantron/bisect_ppx#376]
It seems like this project is not compatible with the latest version of ReScript (9.1) as the Marshall module appears to no longer be available.

```
> rescript build -with-deps

Dependency on @rescript/react
Dependency on bisect_ppx
rescript: [1/3] src/common/bisect_common-Bisect.cmj
FAILED: src/common/bisect_common-Bisect.cmj
File "/home/john/projects/rescript-coverage/node_modules/bisect_ppx/src/common/bisect_common.ml", line 184, characters 3-20:
Error: Unbound module Marshal
FAILED: cannot make progress due to previous errors.
```

Some others are having this issue on the forum as well: https://forum.rescript-lang.org/t/upgrading-from-bs-platform-9-to-rescript-9-1-3-unbound-module-marshal-bisect-ppx/1818

**Comment by aantron** [comment]
Thanks for the report! I'll probably have to either switch to some legitimate format, or vendor `Marshal` to get this fixed. Will try to do it over the weekend.

**Comment by BlueHotDog** [comment]
hey, any update regarding this? trying to upgrade to rescript 9.1 and having this issue.

**Comment by aantron** [comment]
Yes, I basically have a proposed fix but I'm suffering from some permissions problem with npm locally, and in the meantime Travis stopped running the CI tests that was building the BuckleScript test in CI... and the travis-ci.com migration seems broken. A perfect storm of bit rot! Even that shouldn't take that long to fix, but I've been unusually busy in the last few days. I hope to get this done this weekend.

I did start a [GitHub Actions](https://github.com/aantron/bisect_ppx/tree/gha) conversion branch yesterday as one approach to working around the problem, but had to switch to other tasks.

**Comment by aantron** [comment]
This issue is now fixed in `master` by 8437ac24f89b1868d191ee924947774872214dc4.

I'll get the new GitHub Actions setup building the binaries (Travis used to do that before the forced travis.com migration broke that setup). Then, this will go out to npm as Bisect_ppx 2.6.2. I'll ping the issue and the forum when it's out.

**Comment by aantron** [comment]
The fix is now out in npm as [`bisect_ppx@2.6.2`](https://www.npmjs.com/package/bisect_ppx/v/2.6.2).

**Comment by BlueHotDog** [comment]
Amazing! thank you! 🥇 ❤️

**Comment by peterpme** [comment]
Thank you @aantron :heart:
