### ISSUE TITLE
Type errors when building with BISECT_ENABLE

### ISSUE THREAD

**Issue by BlueHotDog** [aantron/bisect_ppx#382]
without the flag, the app compiles. but when this flag is set, i'm getting a bunch of weird type errors like:
```
  24 ┆ | Some(true) =>
  25 ┆   Reducer.updateWithSideEffect({...state, isLoading: true}, _ => {
  26 ┆     Webapi.Dom.window->Webapi.Dom.Window.setLocation(...)
  27 ┆   }`,

  This has type: Dom.window
  Somewhere wanted: int
  ```
  The bs_config looks something like:
  ```
  "ppx-flags": [
    [
      "bisect_ppx/ppx",
      "--exclude-files",
      ".*\\.test\\.res$$",
      "--exclude-files",
      ".*__Stories\\.res$$"
    ],
    "re-formality/ppx",
    [
      "@reasonml-community/graphql-ppx/ppx",
      "-schema=.../schema.gql"
    ]
  ],
  ```

**Comment by BlueHotDog** [comment]
Cool! any chance you could update the #binaries branch meanwhile? the only way i could make it work is by manually replacing the binary but i would love to be on the master/binaries branch to keep working on this

**Comment by aantron** [comment]
> update the #binaries branch meanwhile?

The `binaries` branch gets auto-updated by the CI on each commit to `master`. Is this what you mean, or something else?

**Comment by BlueHotDog** [comment]
weird. i've tried making the dependency from the binaries branch but still getting the error.
When i replace manually it works :(

**Comment by BlueHotDog** [comment]
oopsie. my fault.. had some resolution config downstream.. all works :)

**Comment by aantron** [comment]
This is now in npm as [bisect_ppx@2.7.0](https://www.npmjs.com/package/bisect_ppx).
