### ISSUE TITLE
Better error message on missing files

### ISSUE THREAD

**Issue by vch9** [aantron/bisect_ppx#386]
In our project, we have several targets such as `(targets: foo.ml)`, which are a bunch of `include`. 
However, these files only exist in `_build/`, in my specific case when calling:
```shell
$ bisect-ppx-report cobertura --coverage-path ${COVERAGE_OUTPUT} ${COBERTURA_REPORT}
```
I end up having a:
```
bisect-ppx-report: internal error, uncaught exception:
                   Sys_error("src/[...]/foo.ml: No such file or directory")
```

I don't really know how files are handled in the tool, would there be a convenient way to handle the targeted files? 
Alternatively, could we catch `No such file or directory` and ignore them? Do you know a scenario where ignoring these last is a really bad idea?

**Comment by aantron** [comment]
The error message now looks like

```
Error: cannot find source file 'test.ml' in:
  - .
  - ./_build/default
Hint: consider passing --ignore-missing-files.
```

Thanks for bringing this up.

**Comment by vch9** [comment]
This look way better, thanks :)
