### ISSUE TITLE
Coverage position misplacement in module

### ISSUE THREAD

**Issue by vch9** [aantron/bisect_ppx#387]
I just found this in our test coverage.

![image](https://user-images.githubusercontent.com/32700018/139413760-c869d6f0-2f92-4926-af5a-4e71a23ca872.png)

Shouldn't the coverage position be on the next line ?

**Comment by aantron** [comment]
No, there shouldn't be a coverage point on any line here. Bisect only instruments the expression language (not the module language, and certainly not comments).

I have two most likely initial candidate explanations:

1. The source file and the `.coverage` files are somehow badly out of sync, for example the `.coverage` files come from a different branch than the sources.
2. There is a false location generated for some expression, which just happens to actually be on the line of the comment, rather than where the expression actually is.

**Comment by aantron** [comment]
Are you able to reduce the source file to smaller examples that still exhibit this behavior? Does it occur outside of your overall build?

The content of the comment makes me suspect that this is a module that might be relatively easily taken out of your overall project.

**Comment by vch9** [comment]
I can't have my hands on a computer this week-end but the file (and module) is relatively small yes. I did not manage to reproduce the issue on a minimal example (in a few minutes tbh), but will do very soon.

Also an information I did not mention: the code is preprocessed by ppx_inline_test before bisect_ppx, could the generated code mess up positions ?

**Comment by aantron** [comment]
> Also an information I did not mention: the code is preprocessed by ppx_inline_test before bisect_ppx, could the generated code mess up positions ?

Yes, that's very possible. I don't know what the case is here yet of course, but PPXs have often emitted bad locations in past experience.

**Comment by vch9** [comment]
Here is a minimal example: https://github.com/vch9/bisect_ppx-issue-387

It is most certainly the generated code by `ppx_inline_test`. The ppx produces just before the module the line:
```ocaml
let () = Ppx_inline_test_lib.Runtime.set_lib_and_partition "trie" ""
module Suffix = struct
  ...
end
```

This is I believe the only difference of coverage's location when the preprocessing is enabled or not in this example.

**Comment by aantron** [comment]
Could inspect the AST to get the exact location generated by `ppx_inline_test`? You should be able to run something like `ocamlc -c -dparsetree the_preprocessed_source_file.pp.ml`.

I think the "correct" behavior for PPXs in most cases is to give generated code a ["ghost"](https://github.com/ocaml/ocaml/blob/cce52acc7c7903e92078e9fe40745e11a1b944f0/parsing/location.mli#L28) location, unless it corresponds to some user-written code in a very obvious way. Bisect_ppx knows not to instrument expressions that have ghost locations:

https://github.com/aantron/bisect_ppx/blob/e65ee7faf6a352fb75e26b73cab281f033fa7261/src/ppx/instrument.ml#L185-L192

If it's true that this generated code has a non-ghost location, it might not be deliberate, and this might be a mistake in ppx_inline_test.

**Comment by vch9** [comment]
The generated code does not have a ghost location:
```ocaml
 structure_item (src/trie.ml[4,201+0]..[4,201+0])
    Pstr_value Nonrec
    [
      <def>
        pattern (src/trie.ml[4,201+0]..[4,201+0])
          Ppat_construct "()" (src/trie.ml[4,201+0]..[4,201+0])
          None
        expression (src/trie.ml[4,201+0]..[4,201+0])
          Pexp_apply
          expression (src/trie.ml[4,201+0]..[4,201+0])
            Pexp_ident "Ppx_inline_test_lib.Runtime.set_lib_and_partition" (src/trie.ml[4,201+0]..[4,201+0])
          [
            <arg>
            Nolabel
              expression (src/trie.ml[4,201+0]..[4,201+0])
                Pexp_constant PConst_string("trie",None)
            <arg>
            Nolabel
              expression (src/trie.ml[4,201+0]..[4,201+0])
                Pexp_constant PConst_string("",None)
          ]
    ]
```

The generated code then is instrumented:
```ocaml

let () =
  ___bisect_post_visit___ 0
    (Ppx_inline_test_lib.Runtime.set_lib_and_partition "trie" "")
```

**Comment by aantron** [comment]
Looks like this issue is being handled in https://github.com/janestreet/ppx_inline_test/issues/33, so closing it here.
