### ISSUE TITLE
ReasonML support seems to be broken...

### ISSUE THREAD

**Issue by Lupus** [aantron/bisect_ppx#404]
For .re sources the report is using .re.ml file, which is a binary AST...
![image](https://user-images.githubusercontent.com/105348/184343995-1639e628-240d-4871-ab30-3034ccb88594.png)

bisect_ppx 2.8.1
dune 3.4.1

**Comment by aantron** [comment]
Thank you! This either broke at some point due to how locations are set by the Reason setup in Dune, or maybe we never even tested it on Reason+Dune, but only Reason+bsb.
