### ISSUE TITLE
Some Coverage Files are not Listed on HTML Coverage Overview

### ISSUE THREAD

**Issue by jakobgemmel** [aantron/bisect_ppx#409]
<h1>Problem</h1>

Since we updated biscet_ppx from version 2.7.1 to 2.8.1, there are some coverage files that are not listed on the index.html file anymore. The corresponding coverage html files for the missing files are still created, they are just not listed on the index file.

To give an example, only 4 sub-files of the _domain_ directory are listed with the newest version:

<h3>Version 2.7.1</h3>

![Older_version](https://user-images.githubusercontent.com/63506645/211558277-0bf386c4-ddb0-4f5f-8533-7ed563b323de.png)

<h3>Version 2.8.1</h3>

![Newest_version](https://user-images.githubusercontent.com/63506645/211562971-460e5548-8c64-4765-a6bd-31a1b3adcb3c.png)

<h1>System Information</h1>

- OCaml version: 4.14
- Dune version: 3.3.1

**Comment by aantron** [comment]
This was likely fixed by @lukemaurer in #401, and will be released in Bisect_ppx 2.8.2. Please ping this issue if you try it and it's not fixed!
