### ISSUE TITLE
Proposal: support more mandatory fields from cobertura dtd

### ISSUE THREAD

**Issue by maxim092001** [aantron/bisect_ppx#417]
Hey!

## Proposal

According to [dtd](https://github.com/cobertura/cobertura/blob/0ff963284cecaace30f409a977dccb07c41a5a8f/cobertura/src/site/htdocs/xml/coverage-04.dtd#L4) we do not support some mandatory fields at the moment.

This issue and future PRs are made to add this support.

- [ ] branch-rate
- [ ] branches-covered
- [ ] branches-valid
- [ ] complexity
- [ ] version
- [ ] timestamp

Basically all `#REQUIRED` fields except conditions.

This issue may be considered as epic, I think there will be different PRs for each feature.

## Why?

Some internal/external tools support cobertura using this dtd. There is also [loose version](https://github.com/cobertura/cobertura/blob/0ff963284cecaace30f409a977dccb07c41a5a8f/cobertura/src/site/htdocs/xml/coverage-loose.dtd), but I do not see any problems with the strict version.

Would you be ok with such contribution? @aantron

Thanks!

**Comment by aantron** [comment]
@maxim092001, are any tools actually broken by us not emitting these?

**Comment by maxim092001** [comment]
> @maxim092001, are any tools actually broken by us not emitting these?

Hey!
[`pycobertura`](https://github.com/aconrad/pycobertura/tree/master) is actually broken due to lack of `<packages>` that I added in [PR](https://github.com/aantron/bisect_ppx/pull/420).

I am unaware of other open-source tools that are actually broken due to a lack of fields. However, some internal tools may be broken as they support only [this dtd](https://github.com/cobertura/cobertura/blob/0ff963284cecaace30f409a977dccb07c41a5a8f/cobertura/src/site/htdocs/xml/coverage-04.dtd#L4). 

I don't see why we cannot support it as well, as these fields will be ignored by other XML parsers (GitLab one for example).

**Comment by aantron** [comment]
We can support them, but we need to develop or find a notion of cyclomatic complexity for OCaml. Adding versions or timestamps will complicate the test suite, as we will need to sanitize those from the test output in order to do stable diffs against expected output. We already removed timestamps and version information from the HTML report for this reason. Nobody was actually using it, and it's a maintenance annoyance. The other fields, likewise. Is the extra time spent coding and maintaining worth any factual benefit?

**Comment by maxim092001** [comment]
Hey Anton, sorry for late reply. We had some internal discussions at Bloomberg and solved our issue internally.

I also agree that there will not be a lot of benefit for the community.

I will close this proposal, but thanks for your time!

**Comment by aantron** [comment]
Thank you!
