### ISSUE TITLE
Look into using attributes to control points

### ISSUE THREAD

**Issue by aantron** [aantron/bisect_ppx#83]
Suggested by Alain Frisch: https://sympa.inria.fr/sympa/arc/caml-list/2016-02/msg00044.html

This would be in addition to comments, not instead – there doesn't seem to be a reason to break backwards compatibility.

**Comment by aantron** [comment]
This is a good idea, but it doesn't address any existing need that I am aware of. Saving it for later to avoid bloat.

**Comment by aantron** [comment]
Given the discussion in #130, I say we resurrect and implement this on the way to 2.0.0. Let's move towards deprecating the comments, and removing them completely at some future date. I want to get rid of the lexer. It will make Bisect a safer and more maintainable PPX if it doesn't read concrete syntax, or require lexer work from the maintainers.

Let me know if you have any objections.

**Comment by aantron** [comment]
We should probably emit a warning if a comment is used for several versions, to give people time to adapt.

**Comment by alainfrisch** [comment]
I'm not sure it would be so bad to simply drop the support for comments (and lexer stuff) altogether for the next major version.  The worst that can happen is that some people will see the coverage ratio of their project drop, but fixing that should be rather simple.  It's not like it would break the compilation of other packages and create a cascade of failures on OPAM.

**Comment by aantron** [comment]
I didn't write it out, but I am proposing to drop it in the next major version (2.0.0). We'll warn starting in the next version (1.3.0). The warning is pretty easy to add, I believe. I agree that dropping support for these comments will not cause any disaster, though.

**Comment by rleonid** [comment]
My 2 cents: go ahead and drop them. Causing a disruption to testing code and asking maintainers to spend 10 minutes just thinking about them, I think should have a positive impact on code quality.
