### ISSUE TITLE
4.03 compatibility

### ISSUE THREAD

**Issue by aantron** [aantron/bisect_ppx#88]
```
opam pin add --dev-repo ppx_tools
opam pin add -y .         # In bisect_ppx directory
```

Does not work on `4.03.0+beta1`.

In addition to fixing the Bisect_ppx code, we may have to update previously-released `opam` files to prevent attempts at installing old Bisect_ppx on 4.03.

**Comment by rleonid** [comment]
Yep, hoping that  https://github.com/alainfrisch/ppx_tools/issues/31 gets released soon.
