### ISSUE TITLE
Opam release for 4.03.0 support

### ISSUE THREAD

**Issue by Khady** [aantron/bisect_ppx#95]
Hi,

Is a released on opam planned for version 1.1.0? I think this is the one that supports ocaml 4.03.0.

I also suppose that the constraint on the version of ocaml in the [`opam file`](https://github.com/aantron/bisect_ppx/blob/master/opam/opam#L27) of this repository should be changed to `>= 4.03.0`.

**Comment by aantron** [comment]
Yes, there is a release https://github.com/ocaml/opam-repository/pull/6171, but it was reverted https://github.com/ocaml/opam-repository/pull/6234. I blocked it waiting for word on https://github.com/alainfrisch/ppx_tools/issues/35. The version constraint in the `opam` file is correct; Bisect_ppx 1.1.0 compiles on both 4.02.3 and 4.03.0.

**Comment by Khady** [comment]
Ok, thanks!

2016-05-03 15:48 GMT+02:00 Anton <notifications@github.com>:

**Comment by aantron** [comment]
1.1.0 is now installable from OPAM. Enjoy :)
